---
- name: Configure automation controller
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    # replace this with your GUID
    guid: 4h9rn
  tasks:
  - name: Create an inventory
    awx.awx.inventory:
      name: AWX inventory
      organization: Default
  - name: Add host
    awx.awx.host:
      name: "{{item}}"
      description: "Nodes"
      inventory: AWX inventory
      state: present
    loop: 
      - node1.{{guid}}.internal
      - node2.{{guid}}.internal
      - node3.{{guid}}.internal
